export const CSSCLS = Object.freeze( Object.seal ({
  BODY:                         "body",
  CLASSNAME:                    "classname",
  CODE:                         "code",
  CODEBLOCK:                    "codeblock",
  DECLARATION:                  "declaration",
  DESCRIPTION:                  "description",
  ERROR:                        "error",
  FOOTER:                       "footer",
  H1:                           "h1",
  HEADER:                       "header",
  KEY:                          "key",
  KEYWORD:                      "keyword",
  OPERATOR:                     "operator",
  SMALL:                        "small",
  STRING:                       "string",
  TOKEN:                        "token",
  TYPE:                         "type",
  PLG_SETTINGS_ACTION_BTN:      "dly-nt-strct-action-ribbon-class",
  PLG_SETTINGS_ACTIVE_TAB:      "dly-nt-strct-settings-active-tab",
  PLG_SETTINGS_CONTROL:         "dly-nt-strct-settings-control",
  PLG_SETTINGS_PAGE:            "dly-nt-strct-settings-page",
  PLG_SETTINGS_TAB:             "dly-nt-strct-settings-tab",
  PLG_SETTINGS_TAB_BAR:         "dly-nt-strct-settings-tab-bar",
  PLG_SETTINGS_TAB_NAME:        "dly-nt-strct-settings-tab-name",
  PLG_SETTINGS_TEXT:            "dly-nt-strct-settings-text",
  PLG_SETTINGS_STRUCTURE:       "dly-nt-strct-settings-structure"
}));