// ensure tests will be run in the right order
import "./00.10.mocktest.for.moment.test"
import "./actions/02.01.execute.default.isSpecialWeekKey.test"
import "./actions/02.02.execute.default.patterns.test"
import "./actions/02.03.execute.default.resolve.test"
import "./actions/02.04.execute.default.resolved.test"
import "./actions/02.05.execute.default.createFolderImpl.test"
import "./actions/02.06.execute.default.createFileImpl.test"
import "./actions/02.07.execute.default.createFileData.test"
import "./actions/02.08.execute.default.createFile.test"
import "./actions/02.09.execute.default.createFolder.test"
import "./actions/02.10.execute.default.build.test"
import "./actions/02.11.execute.default.parseStructure.test"
import "./actions/02.12.execute.default.executeDefault.test"