import   typescript    from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import   commonjs      from "@rollup/plugin-commonjs";
import   json          from "@rollup/plugin-json";
import   strip         from '@rollup/plugin-strip';
import   terser        from "@rollup/plugin-terser";

const isProd = ( process.env.BUILD === "production" );

const banner = 
`/*
 *  THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
 *  If you want to view the source, visit the plugins github repository
 */
`;

export default {
  input: "src/lib/main.ts",
  output: {
    dir: ".",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: [
    "obsidian",
    "@codemirror/state",
    "@codemirror/view",
    "@codemirror/language",
    "@codemirror/search",
    "@codemirror/autocomplete"
  ],
  plugins: [
    json(),
    typescript({tsconfig: ".config/tsconfig.build.json" }),
    nodeResolve({browser: true}),
    commonjs(),
    // Strip console and debugger statements first
    isProd && strip({
      include: '**/*.(js|ts)',
      exclude: 'src/lib/main.ts', // console.logging: "Plugin loaded" should be available!
      functions: ['console.*'],
      debugger: true
    }),
    // Remove all remaining comments
    isProd && terser({
      compress: false, // obsidian demands not to obfuscate code
      mangle: false,   // obsidian demands not to obfuscate code
      format: {
        comments: false,
        beautify: true   // sorgt für ordentlich formatierten, mehrzeiligen Code
      }
    })
  ]
};